### ISSUE TITLE
`OutWatch.render()` should render inside the target element, not patch it

### ISSUE THREAD

**Issue by ngthanhtrung** [OutWatch/outwatch#10]
As in the title, I think the target element should act as a canvas to be rendered inside. This is the behavior of all virtual DOM libraries out there. Currently _OutWatch_ patches the target element, which is quite strange to me and it makes element styling a bit harder.

**Comment by LukaJCB** [comment]
You make a very good point! Should be fairly easy to implement :)

**Comment by LukaJCB** [comment]
Fixed by bd302559889b902af08d1cf1bdd2a6d870a6d912 👍
