### ISSUE TITLE
Use snabbdom thunk method

### ISSUE THREAD

**Issue by cornerman** [OutWatch/outwatch#104]
Besides just creating a new `VNodeProxy` via `h` function, we could use [thunks](https://www.npmjs.com/package/snabbdom#thunks) in snabbdom. This is a performance strategy, where the proxy is only created when the arguments it depends on change.

So, the diffing and proxy creation is saved, when we can provide a set of arguments, which sufficiently define the rendered element. Maybe we can support this?

**Comment by fdietze** [comment]
Relevant for going even further: https://github.com/raquo/Laminar/issues/14

**Comment by cornerman** [comment]
We can use an observable with distinctUntilChanged instead, see #197.
