### ISSUE TITLE
Usage of scalac option `-Xcheckinit`

### ISSUE THREAD

**Issue by cornerman** [OutWatch/outwatch#106]
The option `-Xcheckinit` introduces runtime checks for uninitialized values in a trait and throws a exception with a meaningful message if the value is used before initialization.

Compiling to javascript, the minified code contains these checks and furthermore introduces a function that is called when accessing this value. Should we remove this because of performance and bundle size or should we keep it?

**Comment by raquo** [comment]
I'd say remove the flag. It doesn't feel right to have onerous runtime checks like this, at least not in production. I guess you could only enable it in fastOptJS and/or in tests. Although I personally try to keep the difference between prod and dev to a minimum.

**Comment by raquo** [comment]
Hm. As a dependency on someone's project, Outwatch gets compiled into intermediate scala.js representation files, not into JVM bytecode. I wonder if this compiler option even affects those sjsir files, or if it is the consuming project's flag that matters instead.

**Comment by cornerman** [comment]
I think you are right and quoting from the link you provided: "It is inadvisable to use this flag outside of testing. It adds significantly to the code size by putting a wrapper around all potentially uninitialized field accesses". So we should remove it, but I am also not sure how it works in dependent applications.
