### ISSUE TITLE
Usefulness of HandlerFactories

### ISSUE THREAD

**Issue by cornerman** [OutWatch/outwatch#128]
We have [HandlerFactories](https://github.com/OutWatch/outwatch/blob/master/src/main/scala/outwatch/dom/HandlerFactories.scala) that add method for "easier" creation of event handlers. This list will never be complete and therefore makes an inconsistent API for users. When working with the dom, I have the dom import from scalajs  there anyhow.

When I see code like this and am new to the code, I directly wonder whether these two Handler creations behave the same:
```scala
import org.scalajs.dom

val keyHandler = Handler.keyboardEvents // Handler.create[dom.KeyboardEvent]
val storageHandler = Handler.create[dom.StorageEvent]
```

Does this really add value?

**Comment by mariusmuja** [comment]
I don't find them particularly useful, I always use `Handler.create[T]`, I find it more clear.

**Comment by fdietze** [comment]
Agreed, this makes it more transparent and simpler.

**Comment by cornerman** [comment]
I think we can remove them without deprecation, as they were not part of the last release, right?
