### ISSUE TITLE
Add every HTML5 attribute and event emitter builder

### ISSUE THREAD

**Issue by thSoft** [OutWatch/outwatch#13]
See:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
- https://developer.mozilla.org/en-US/docs/Web/Events

**Comment by LukaJCB** [comment]
Added a bunch of new events and attributes in v0.8.0. :)

**Comment by PerWiklander** [comment]
All attributes on the doc list should be added by #16.
Some more events where added as well, but I see now that the doc list has more that are missing.
