### ISSUE TITLE
Remove varargs from Handler and Pipe creation

### ISSUE THREAD

**Issue by LukaJCB** [OutWatch/outwatch#136]
I don't think these serve any purpose except and I made a mistake in adding them. Let's get rid of them!

**Comment by mariusmuja** [comment]
I find the option of having an default value on a `Handler` useful in setting an initial state for the UI before anything else gets emitted to change that state. 

I don't think we need varargs for that, one initial value should be enough (but I don't see any problem with the varargs option either).

**Comment by LukaJCB** [comment]
Yeah, to clarify I didn't mean get rid of startWith, but  it really should be one or zero arguments and varargs aren't the best way to represent that.

**Comment by doofin** [comment]
Varargs really make me headache when i start to use scala! ( I am a old haskeller) ,especially the _:* conversion

**Comment by cornerman** [comment]
Fixed with #203
