### ISSUE TITLE
Play integration example

### ISSUE THREAD

**Issue by guizmaii** [OutWatch/outwatch#14]
Hi,

First, your project is very interesting ! Thank you for your work ! :)

Next, do you have an example of how to integrate an OutWatch projet in a Play one ? 

I saw this kind of ScalaJS integration: https://github.com/vmunier/play-with-scalajs-example (which I already use) with a "frontend" project and a "backend" one, but it uses twirl. 
Is it possible to not use twirl and just serve the output of OutWatch "compilation" ?

Thanks,
Jules

**Comment by LukaJCB** [comment]
It's most definitely possible! If you check out the docs, there's a pretty easy way to get started with just an `index.html`. You could just serve that index.html from your Play app. :)

**Comment by PerWiklander** [comment]
To clarify, OutWatch does not support server side rendering (yet). For something that has JVM support and will feel very much the same, without the whole Rx functionality though, have a look at [ScalaTags](https://github.com/lihaoyi/scalatags)
