### ISSUE TITLE
Create Handler from Observable and Sink

### ISSUE THREAD

**Issue by GRBurst** [OutWatch/outwatch#143]
Hey there,

I want to create a `Handler` that is manually composed from an `Observable[T]` and a `Sink[T]` of the same type. It seems like `ObservableSink` is what I want, but since it is private I can not access it.

In my example I want to create a Handler within a case class like this:
```
val hand: Handler[T] = {
  val obs: Observable[T] = myReader(Object.arg)
  val sink: Sink[T] = myWriter(Object.arg)
  Sink.ObservableSink(sink, obs)
}
```

So how can I achieve that? Why is `ObservableSink` or the `Handler` and `Pipe` factories private? 

Thanks for your help in advance!

Kind regards

**Comment by doofin** [comment]
+1,I also encounter this problem when trying to make the observable "share"

**Comment by fdietze** [comment]
I agree. At least `Handler` and `Pipe` factories should be public (I'm talking about the current master here). @LukaJCB @mariusmuja What exactly were the original reasons to make them private?

**Comment by cornerman** [comment]
See discussion and possible solution in: #145
