### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by guizmaii** [OutWatch/outwatch#15]
I didn't find anything in outwatch (nor in rxscala-js) to handle websockets.
RxJS provides this : https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/src/dom/websocket.js

Do you plan to add the support of websockets ?

I found this : https://github.com/Reactive-Extensions/RxJS/issues/112#issuecomment-53477208
but I'm not able to implement it with ScalaJS and rxscala-js :(

Thanks,
Jules

**Comment by LukaJCB** [comment]
There's a Websocket case class in the `outwatch.util` package. It's currently not well documented, but it's source is very simple and explained in brief here: https://outwatch.github.io/sinks.html. For very complex interaction with websockets, it might be best to implement your own wrapper around the websocket.

**Comment by guizmaii** [comment]
Ok thanks :)
