### ISSUE TITLE
Use package outwatch, instead of outwatch.dom

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#168]
Importing `outwatch.dom` can be confused with `org.scalajs.dom`. (https://gitter.im/OutWatch/Lobby?at=5a68802ee0141226508680f7)

I propose to put everything in the package `outwatch`, so the imports look like:

```scala
import outwatch._
import outwatch.dsl._
```

**Comment by mariusmuja** [comment]
This seems like a good idea to me.

**Comment by cornerman** [comment]
Fixed in #355
