### ISSUE TITLE
Remove `child <--` and `children <--` syntax ?

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#169]
We could allow to use  `Observable[VNode]` and `Observable[Seq[VNode]` directly as modifiers:

```scala
val h = Handler.create[String]().unsafeRunSync()
div(
  h.map(p(_))
)
```

I understand that the `<--` notation signals reactive updates to the DOM, but in many cases I wished, I could write the observables directly in my tags.

**Comment by mariusmuja** [comment]
I've been giving this some though, I can see some pros and cons:

Pros:
*  there is no `child` or `children`  HTML syntax, so the VDOM DSL would become closer to the actual HTML, arguably simpler
* no more distinction between `child` and `children`, need a single node to update, use an `Observable[VNode]`, need a list, use `Observable[Seq[VNode]]`

Cons: 
  * it might make it harder to spot where reactive DOM updates happen (not longer possible to search for `child <--` or `children <--`

Implementation-wise it's trivial, we only need to provide the `AsVDomModifier` type classes for `Observable[VNode]` and `Observable[Seq[VNode]]`, I did that on my monix branch to try it out: https://github.com/mariusmuja/outwatch/commit/725ab77bfbb58074f1f1d3413f58038cdc9f68ab

Overall, I tent to agree with this proposal. What do others think? @LukaJCB @cornerman

**Comment by cornerman** [comment]
I am in favor of this proposal! The distinction between child and children always felt arbitrary and I tend to forget them :)
