### ISSUE TITLE
provide convenient helpers for event.preventDefault

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#188]
something like
```scala
div(onClick.preventDefault --> ... )
```

```scala
div(onClick.preventDefault("foo") --> ... )
```

**Comment by cornerman** [comment]
This is possible now with EmitterOps, see https://github.com/OutWatch/outwatch/blob/e86ee2e2f61917bf7785296fcba6eb7e9f4c90ec/src/main/scala/outwatch/dom/helpers/EmitterOps.scala#L10
