### ISSUE TITLE
Call event.stopPropagation by default in event handlers

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#189]
Most of the time this is confusing:

```scala
div(
  onClick --> ...,
  div(onClick --> ...)
)
```

Currently, clicking on the inner `div` also triggers the outer `onClick` handler.

**Comment by cornerman** [comment]
Agree that this is confusing default-behaviour. How could we write the exception when you want it to propagate? Maybe `onClick.withPropagation`?

**Comment by fdietze** [comment]
Yes, I like that.

**Comment by raquo** [comment]
I agree that this would be convenient more often than not, but it would
also be a pretty significant departure from expected DOM behaviour.

Do you know if any other DOM UI library, in JS or Scala.js is doing this?

**Comment by fdietze** [comment]
I searched a bit and found this: https://css-tricks.com/dangers-stopping-event-propagation/

In none of my past projects I relied on event bubbling. But I can understand that some libraries do.

I initially proposed stopping event propagation because it solves #193:

When modifying the dom from inside an event handler, the current event can bubble into the  newly created dom and trigger handlers which have nothing to do with the current event. I had exactly this issue and it was very very hard to debug. It can happen easily when switching a view based on an Observable[Boolean], where the view contains click handlers which write into the observable. I think this is a common pattern.

**Comment by fdietze** [comment]
The problem is more fundamental: https://jsfiddle.net/3bjqyx2g/

I find this a bit crazy, that it works like that.

**Comment by cornerman** [comment]
Good example, just updated it to be more readable: https://jsfiddle.net/3bjqyx2g/1/

**Comment by raquo** [comment]
That jsfiddle example does not surprise me at all, that's how I expect things to work in JS DOM.

#193 does confuse me because it _seems_ like the parent onClick is defined on a element that doesn't exist at the time of the event, but because of a mismatch between virtual and real elements this assumption is not correct.

I don't have a strong opinion on whether Outwatch should stopPropagation by default. In general I would be leaning against doing that, but that virtualdom issue does seem worth addressing or at least documenting.

**Comment by fdietze** [comment]
I'm wondering if other popular vdom libraries prevent issues like this one.

**Comment by fdietze** [comment]
I tried to reproduce with React: https://codepen.io/anon/pen/OZaeyv?editors=0010

I think React does not have this problem, since it starts the rendering asynchronously.

Maybe related: https://reactjs.org/docs/faq-state.html#when-is-setstate-asynchronous

**Comment by cornerman** [comment]
I think, we should not do this, because it would be against everything people know from the dom event system. If needed, one can do it in their application.

So I am closing this one, but please feel free to reopen, if we need more discussion on this one.
