### ISSUE TITLE
eliminate :=? operator

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#190]
Maybe with implicits its possible to eliminate the `:=?` operator, to be able to write this:
```scala
id := Some("myId")
```

It's one of the few operators we have and sometimes unintuitive to use.

**Comment by cornerman** [comment]
This could just be done like this:

```scala
Option("myId").map(id := _)
```

**Comment by cornerman** [comment]
What about the `?=` operator? This can be done with an Obserable[Option[VDomModifier]].

**Comment by cornerman** [comment]
I am not sure anymore whether we should remove this operator, it is actually quite nice and faster to write than `option.map(attr := _)`. Should we maybe just keep it?

**Comment by fdietze** [comment]
I agree, there should be an operator. If it can't be `:=`, then it should be `:=?`.

**Comment by cornerman** [comment]
So we keep `:=?` and just removed `?=`.
