### ISSUE TITLE
Boolean selection of attribute values

### ISSUE THREAD

**Issue by PerWiklander** [OutWatch/outwatch#21]
This would make it easier to include an attribute or not depending on a boolean value (taken from scalajs-react).

```scala
def hasFocus: Boolean = ???

input(hasFocus ?= (value := "I have a value only when I'm focused"))
```

Do we have some Observable magic to take into account here? Would we want an `Observable[Boolean]` to be able to do the toggling?

**Comment by LukaJCB** [comment]
If we do something like this, I think we shouldn't introduce too much new syntax. Either we have `hasFocus` be a `Boolean` and bind it only once, OR (which I think makes more sense) have `hasFocus` be an `Observable[Boolean]` and add or remove the value on every emission of the source Observable. Both should be fairly easy to implement. 

I'm not a hundred percent sold on the `?=` operator, but I don't have a better suggestion yet, I'll try to come up with something. :)

**Comment by PerWiklander** [comment]
Scalajs-react just came out with the long awaited `1.0.0-RC1` and in the enormous change log I just saw this:

> All vdom now has .when(condition) and .unless(condition), allowing you to conditionally include/omit dom. This replaces the cond ?= (vdom) syntax.

Interesting. So the above example would now be written as:

```scala
def hasFocus: Boolean = ???

input(
  (value := "I have a value only when I'm focused").when(hasFocus)
)
```

**Comment by PerWiklander** [comment]
And of course:

```scala
def hasFocus: Boolean = ???

input(
  (value := "I have a value only when I'm NOT focused").unless(hasFocus)
)
```

**Comment by gaydenko** [comment]
Why not just
   `if (hasFocus) input(...)`
?

**Comment by PerWiklander** [comment]
The point is to not repeat code that is the same in both branches of the if statement. Pretend that you have more than one boolean to take into account. That will give you an explosion of if/else statements.

**Comment by gaydenko** [comment]
Then
```
value := { if (hasFocus) "foo" else "" }
```

**Comment by PerWiklander** [comment]
No one said it can't be done with an if statement. But just as you could do all your `for {}` statements with `flatMap`, a little sugar cuts down on the logic overload. 

I argue that `(value := "foo").when(hasFocus)` is more clear than `value := { if (hasFocus) "foo" else "" }` when the `else` has no value. Besides, wouldn't the latter give an empty `value=""` in the DOM? That might not what a user wants.

**Comment by gaydenko** [comment]
I guess, any profit form `.when` or similar isn't comparable with the profit form `for`-comprehension syntax. At any case the first is far below that level when new API can be introduced. There are few things we all must avoid as we can: new/change API, new dimension in states set, new abstraction... To my taste the case under discussion is the one to follow these mantras :)

**Comment by PerWiklander** [comment]
So how do you propose a user of this library express the intention of

`input(_include an attribute here IFF a particular boolean is true_)`

without having to use an if/else structure like
```
if(hasFocus) {
  input(...)
} else {
  input(...)
}
```

keeping in mind what I said about cartesian products of boolean combinations and unwanted empty attributes?

And regarding "the level where new API can be introduced", why do we have this lib at all when we could just as well write it as

```
val vnode = h('input', literal(props = if(hasFocus) literal(value = 'foo') else literal()), ...)
```
?

**Comment by PerWiklander** [comment]
Oh, and I forgot about the fact that we were leaning towards having `hasFocus` be an `Observable[Boolean]` and not a `Boolean`.

**Comment by gaydenko** [comment]
It is ordinary case, isn't it? Then we use `map`/`flatMap` or `for`-comprehesion. We often use them at any case.

**Comment by gaydenko** [comment]
As for empty attribute - well, I guess @LukaJCB can say us which value we can use as an empty attribute (and empty VNode). It can be handy at any case to keep code functional and avoid Option.

**Comment by PerWiklander** [comment]
So how would I write it then? Like this?:

```
input(
  value <-- hasFocus.map { f =>
    if(f) "I have a value only when I'm focused"
    else EmptyAttributeValue
  }
)
```

**Comment by gaydenko** [comment]
Some kind of, if there is the only observable needed to be pulled out of the container (that is Observable). At my case it is more often I need take out from containers more than a single thing :)

**Comment by gaydenko** [comment]
```
for {
  data1 <- obs1
  data2 <- obs2(data1)
  data3 <- obs3(data1, data2)
} yield {
  some view form datas
}
```

**Comment by LukaJCB** [comment]
Out of all these, I think I still like the original idea best, where we had `?=` bind to an `Observable[Boolean]`. I'm gonna have some time on me this weekend and would like to tackle it :)

**Comment by PerWiklander** [comment]
Would you implement `?=` with an implicit conversion from `Observable[Boolean]` to some `ObservableBooleanAttribute`?

**Comment by LukaJCB** [comment]
@PerWiklander Yes, that's what I plan to do :) Or do you have a better idea?

**Comment by PerWiklander** [comment]
Nope, I guess that is the best way. And then importing the implicit stuff can be optional, and not effect the purists ;-) If you do `?=` first I can create a PR for `when` and `unless` and we can see how they feel.

**Comment by LukaJCB** [comment]
Great idea! They're in master now :)

**Comment by PerWiklander** [comment]
Regarding

```scala
 // Maybe find a better way to represent empty attributes
 +  private val emptyAttribute = Attribute("hidden", "")
```

a couple of case objects for `EmptyAttribute` and `EmptyElement` would probably be a good idea.

**Comment by gaydenko** [comment]
Ha, that empty attribute also has caught my look :)
I guess empty attribute (as well as empty node) can be a part of public API for the cases they are calculated and, say, represented as a collection. Yes, we can wrap them with `Option` and then `collect { case Some(att) => att }`, but empty values would be more readable. What do you think?
