### ISSUE TITLE
Merging emitter functions prevents stopImmediatePropagation

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#217]
https://github.com/OutWatch/outwatch/blob/b6e6d8600686c0e1af729ae42d30d885cb3bd049/src/main/scala/outwatch/dom/helpers/Snabbdom.scala#L174

**Comment by cornerman** [comment]
We need to send a list of emitter functions (in order) to snabbdom instead of just one.

**Comment by cornerman** [comment]
This will never work with snabbdom, because snabbdom creates one(!) eventlistener for each occuring event type.

So, my best guess would be to remove stopImmediatePropagation from our API, as we cannot make this work. You can still implement this functionality in your own application.

**Comment by cornerman** [comment]
As long as we are using snabbdom as is, we cannot fix it.
