### ISSUE TITLE
Optional elements and attributes

### ISSUE THREAD

**Issue by PerWiklander** [OutWatch/outwatch#22]
This would make it easier to include an element or not depending on if an `Option` (or `js.UndefOr`) is defined or not (taken from scalajs-react).
This would work with implicit conversion,  like `StringNode` today.

```scala
case class User(
  profileUrl: String,
  favColor: Option[String]
)

val loggedInUser: Option[User] = ???

div(
  h3("Welcome"),
  loggedInUser.map(user =>
    a(
      href := user.profileUrl,
      style := user.favColor.map(c => s"background-color: $c")
      "My Profile"
    )
  )
)
```

**Comment by LukaJCB** [comment]
This seems like a pretty neat idea! Implementing it would be fairly trivial even. I can prepare something pretty soon, or you can send a PR, if you'd like :)

**Comment by PerWiklander** [comment]
And of course the new scalajs-react `1.0.0-RC1` has a twist in this as well. Just for our consideration I guess. Japgolly has become a lot more cautious with implicit now, it seems. So now it is like this instead (taken from https://github.com/japgolly/scalajs-react/blob/master/doc/VDOM.md#conditional-vdom):

> Option / js.UndefOr - Append .whenDefined.

```scala
val loggedInUser: Option[User] = ???

<.div(
  <.h3("Welcome"),
  loggedInUser.map(user =>
    <.a(^.href := user.profileUrl, "My Profile")
  ).whenDefined
)
```

> This doesn't just work for Option[vdom], you can also use it in place of .map for improved readability and efficiency. The above example then becomes:

```scala
val loggedInUser: Option[User] = ???

<.div(
  <.h3("Welcome"),
  loggedInUser.whenDefined(user =>
    <.a(^.href := user.profileUrl, "My Profile")
  )
)
```
