### ISSUE TITLE
managed for subscriptions should only run onInsert

### ISSUE THREAD

**Issue by cornerman** [OutWatch/outwatch#220]
Currently runs IO, when the VDomModifiers is used, but we could delay the subscription until the element is actually inserted into the dom.

**Comment by mariusmuja** [comment]
> Currently runs IO, when the VDomModifiers is used

The IO runs at the edge of the program (on a snabbdom patch), not when it's used, so the subscription should only happen when the element is inserted/patched.

**Comment by cornerman** [comment]
Sorry, my description is really badly written, but  I meant `run` when I said `used` :)

Maybe, you are right. I just thought `managed` uses `onInsert` and was a bit confused when I looked into the code. This is why I opened this issue. Given that the IO really runs at the edge of the program, it really is just before being inserted. But given that we use the `onDestroy` hook for canceling, `onInsert` would have looked nicely symmetric.

**Comment by mariusmuja** [comment]
`managed` is just for canceling a `Cancelable`, so all it really needs is a destroy/terminate/shutdown hook. The 'Cancelable` doesn't always have to be from a subscription, it could be a from a cancelable IO (performing a web request for example) that we want to cancel when the node it destroyed.

**Comment by cornerman** [comment]
Okay, sounds good then. Thanks!
