### ISSUE TITLE
Outwatch.renderInto() uses a common magic value

### ISSUE THREAD

**Issue by marklister** [OutWatch/outwatch#223]
I had difficulty using `Outwatch.renderInto` so I eventually hacked a solution using `renderReplace`.  It turns out I was using an element id `"app"` and renderInto was creating one with the same id.

Perhaps the magic value "app" should get changed to something less likely to collide in the wild? 

```
  def renderInto(element: dom.Element, vNode: VNode)(implicit s: Scheduler): IO[Unit] = for {
    node <- vNode
    _ <- IO {
      val elem = dom.document.createElement("app")
      element.appendChild(elem)
      patch(elem, node.toSnabbdom)
    }
  } yield ()
```

**Comment by cornerman** [comment]
Good catch! Thanks for reporting, I have made a PR using a hopefully uncommon name `_outwatch_app_` (https://github.com/OutWatch/outwatch/pull/224).

**Comment by cornerman** [comment]
Hmm, after talking with @fdietze, `document.createElement(tagName)` does not set the element id, but the tagName of the created element. It results in `<app></app>` (not sure whether this is a good tag-choice). So the problem is maybe somewhere else?

@marklister can you give an example where it breaks?

**Comment by marklister** [comment]
Here's working code:
```
private lazy val renderFunc = (pg: Future[VNode]) => {
    pg map { p =>
      OutWatch.renderReplace("#app", div(id := "app", p)).unsafeRunSync()
    }
  }
```
if I render like this : `OutWatch.renderInto("#app",p).unsafeRunSync()` 

I get dom elements concated on a second render.

If I do this:

`OutWatch.renderReplace("#app",  p).unsafeRunSync()`

Only the first render succeeds.  Subsequent renders lack the 'app' target.  My intuition of renderInto or renderReplace was that one would be would simply repeatable.

my template contains a `<div id="app">`

When I spotted the magic value, sometime after I wrote this code I had an "Ahah!" moment without interrogating it too deeply.

**Comment by marklister** [comment]
The `app` element appears to have been removed from the current html spec.  Perhaps you might consider another?

**Comment by fdietze** [comment]
I think there is a misunderstanding in the usage of the `OutWatch.render*` methods. The render-function is supposed to be called only *once* at the end of your program.

The VNodes are constructed to to only *describe* the data-flow of the user interface (with Observables).  Rerendering happens automatically when the observables trigger. Outwatch automatically handles the patching of the dom for you.

**Comment by marklister** [comment]
Bear in mind the code I posted was the render func of my router on a multi page app. And it's a bit of a hybrid having been ported from a scalatags dom thunking monstrosity. It works well like this, I'm very happy.
