### ISSUE TITLE
ClassSet

### ISSUE THREAD

**Issue by PerWiklander** [OutWatch/outwatch#23]
This makes it easier to include a bunch of classes depending on boolean values (taken from scalars-react).

```scala
div(
  classSet(
    "message"           -> true,
    "message-active"    -> true,
    "message-important" -> props.isImportant,
    "message-read"      -> props.isRead),
  props.message)

// Or for convenience, put all constants in the first arg:
div(
  classSet1(
    "message message-active",
    "message-important" -> props.isImportant,
    "message-read"      -> props.isRead),
  props.message)
```
Do we have some Observable magic to take into account here? Would we want an `Observable[Boolean]` to be able to do the toggling?

**Comment by LukaJCB** [comment]
I'm not sure what exactly can be toggled here?

**Comment by PerWiklander** [comment]
The classes that have a Boolean true in the tuple will be included in the class string. So you could have a class attribute value of "disabled large button" but you only want "disabled" in there depending on a Boolean.

 /Per

**Comment by fdietze** [comment]
Snabbdom supports this feature already: https://github.com/snabbdom/snabbdom#the-class-module

**Comment by PerWiklander** [comment]
So we need some glue code that translates a `Seq[(String, Boolean)]` into a JS literal? How about `Observable[Boolean]`?

**Comment by fdietze** [comment]
First the DataObject (https://github.com/OutWatch/outwatch/blob/master/src/main/scala/snabbdom/h.scala#L52) needs an additional field `class:js.Dictionary[Boolean]`.

Supporting `Boolean` and `Observable[Boolean]` on the usage side sounds good to me.

**Comment by cornerman** [comment]
We will add a `toggle` method for attributes (including classes), which should improve this significantly (see #445). With this, I do not see a need for supporting the classset as proposed.

Therefore, I am closing this issue. Feel free to reply or reopen if there is more to discuss.
