### ISSUE TITLE
Update Sanbbdom to 0.6.7 to get better boolean attribute handling

### ISSUE THREAD

**Issue by PerWiklander** [OutWatch/outwatch#24]
Snabbdom has made a new [release](https://github.com/snabbdom/snabbdom/releases/tag/v0.6.6) that makes boolean attributes behave according to spec.

We should update Sanbbdom to `0.6.7` and add a test that checks that the it works as we want, that is boolean attributes should have no value in the DOM but be added or removed according to `true` or `false`.

**Comment by PerWiklander** [comment]
I see we're still on the `0.5.4` version, before their TypeScript rewrite (`0.6.1`) . Are there any known problems with updating?

**Comment by PerWiklander** [comment]
Snabbdom has released 0.6.7 now, that actually updates the dist files as well (which 0.6.6 did not).

**Comment by LukaJCB** [comment]
Done :)
