### ISSUE TITLE
Seems elements that disappear (new one redraws) still continue work with (consume) streams

### ISSUE THREAD

**Issue by MercurieVV** [OutWatch/outwatch#244]
Here is piece of code 
```
    val listItemsObs: Observable[List[Item]] = ...
    val texts: Observable[Texts] = listItemsObs.map(/*actually call to web here*/)

    var cntr= 0
    <.div(
      listItems(listItemsObs, textIdO),
      <.div(^.child <-- texts
        .map(t => {
          println("list te")
          <.div(
            <.div(^.child <-- textIdO.doOnNext(t => println("mdd " + t + " " + {cntr=cntr+1;cntr})).map(t => t.title)),
            <.div(<.textArea(t.en.getOrElse("").toString, ^.onInput.value --> onTextEdit.mapSink(s => {
              val tc = t.copy(en = Some(s))
              println(tc)
              tc
            }))),
          )
        })
      )
    )

  private def listItems(menuItems: Observable[List[Item]], onClick: Handler[Item]) = {
    <.ul(
      ^.children <-- menuItems.doOnNext(t => println(t + " gg")).map(items => items.map(item =>
        <.li(
          ^.onClick(item) --> onClick.mapSink(f=>{
            println("xxx")
            f
          }),
          item.title,
        )
      ))
    )
  }

```
Several times I emit `textIdO`. Every its event create event for `texts: Observable[Texts]`, so div with text redraws (we can see it in logs by `println("list te")`). Its div internal element "consume" `textIdO`. But what is odd, lines printed by `println("mdd " + t + " " + {cntr=cntr+1;cntr})` (see logs started with "mdd ") increases.

> xxx texts_ui-fastopt.js:63910:7
> list te texts_ui-fastopt.js:63910:7
> xxx texts_ui-fastopt.js:63910:7
> mdd Item((emails,amz_rate_product_reminder_body),emails.amz_rate_product_reminder_body) 1 texts_ui-fastopt.js:63910:7
> list te texts_ui-fastopt.js:63910:7
> xxx texts_ui-fastopt.js:63910:7
> mdd Item((emails,amz_rate_reminder_subject),emails.amz_rate_reminder_subject) 2 texts_ui-fastopt.js:63910:7
> mdd Item((emails,amz_rate_reminder_subject),emails.amz_rate_reminder_subject) 3 texts_ui-fastopt.js:63910:7
> list te texts_ui-fastopt.js:63910:7
> xxx texts_ui-fastopt.js:63910:7
> mdd Item((emails,amz_confirmation_subject),emails.amz_confirmation_subject) 4 texts_ui-fastopt.js:63910:7
> mdd Item((emails,amz_confirmation_subject),emails.amz_confirmation_subject) 5 texts_ui-fastopt.js:63910:7
> mdd Item((emails,amz_confirmation_subject),emails.amz_confirmation_subject) 6 texts_ui-fastopt.js:63910:7
> list te texts_ui-fastopt.js:63910:7

So, I suppose with redraw, consumers not destroyed, but still consume and process events. Am I doing something wrong?

**Comment by cornerman** [comment]
What version of outwatch are you using? There might have been a bug with subscriptions in an older version. Could you try out the current master and see whether the problem still persists? In general, I would recommend updating outwatch to a newer version. It is much more stable.

You can try it out like this:
```
resolvers += "jitpack" at "https://jitpack.io"
libraryDependencies += "com.github.outwatch" % "outwatch" % "master-SNAPSHOT"
```

Also: Where did you get this syntax with `<` and `^` from? At first glance, I was not even sure that it is outwatch :)

**Comment by MercurieVV** [comment]
Thanks for response.
Yes, master version works much better. It actually log twice (probably its my side issue), but anyway its much better than constantly increase logs.
Im using "1.0.0-RC2".

Yep, pardon for this `<` `^` syntax. :) I just copied it from scalajs-react. I think its easier to read (they also use it to not have issues with mixing context).
```  val < = dsl.tags
  val ^ = dsl.attributes
```

**Comment by cornerman** [comment]
Great! Still logging twice sounds odd - which log is it? 

Yeah, the `<` `^` is definitely nice for not cluttering the current scope!

**Comment by cornerman** [comment]
I cannot reproduce this with the current master. Please reopen if the problem still persists.
