### ISSUE TITLE
Type in doc page menu too large

### ISSUE THREAD

**Issue by PerWiklander** [OutWatch/outwatch#25]
![screenshot 2017-03-28 13 59 24](https://cloud.githubusercontent.com/assets/391989/24403818/e1392000-13be-11e7-8fe9-653e4cfc0401.png)

**Comment by gaydenko** [comment]
Yes, confirming. At my case `PureScript` is also over a text.

**Comment by LukaJCB** [comment]
Thanks for pointing this out :) Fixed

**Comment by MiracleBlue** [comment]
Howdy, I seem to be having the same issue, except the text is even larger for me than the above examples.  Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/23368/24783553/6c4226dc-1b90-11e7-8fc5-b74e01b07a72.png)
