### ISSUE TITLE
Rename developer-facing Types

### ISSUE THREAD

**Issue by fdietze** [outwatch/outwatch#253]
For example, I suggest to rename:

* `VDomModifier` to `Modifier`

Any more suggestions?

**Comment by cornerman** [comment]
I think that is a good idea, I do not like the VDomModifier name either. What would you do about `VNode`? `VNode` has the `V` prefix, but `Modifier` would not. Would `VModifier` make sense or should we have `Node` or is `Node` a too generic name.

**Comment by fdietze** [comment]
I think `VNode` is fine. It never felt too long to write. `Node` seems to be indeed to generic.

**Comment by busti** [comment]
I think we should have `VNode` and `VModifier`. It communicates more clearly that they belong to the same Concept.  
We should not rename `VNode` to `Node` since that would cause collisions with `dom.Node` which is often used in the same context.

**Comment by fdietze** [comment]
> I think we should have `VNode` and `VModifier`. It communicates more clearly that they belong to the same Concept. We should not rename `VNode` to `Node` since that would cause collisions with `dom.Node` which is often used in the same context.

@busti agreed to everything you said!

**Comment by cornerman** [comment]
I have this change hidden in a huge PR - again - that is #441. There I changed `VDomModifier` to `Modifier`. Should I change it to `VModifier` then? I like that is symmetric to `VNode`.

**Comment by fdietze** [comment]
Yes, just do it.
