### ISSUE TITLE
Renaming: Outwatch vs. OutWatch

### ISSUE THREAD

**Issue by cornerman** [outwatch/outwatch#268]
We have the object `OutWatch` for all `render` methods. But then we have things like `OutwatchAttributes`, `OutwatchTracing`, `OutwatchSpec`.

We should align those names to either have case `OutWatch` or `Outwatch` consitently. What do you all prefer?

**Comment by marklister** [comment]
I prefer Outwatch.  "Outwatch" itself is a legitimate English word and capitalizing the first letter would make it a proper noun.

**Comment by cornerman** [comment]
> I prefer Outwatch. 

I tend to feel the same. @LukaJCB What do you think?

We might want to rename the github organization then, too :)

**Comment by LukaJCB** [comment]
I'm fine with either :)
