### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fdietze** [outwatch/outwatch#276]
We need more documentation. I already wrote a lot about the basic concepts, but there is a lot of documentation missing. Here is an incomplete list to have an idea what to work on:

As a general idea, let's link almost all topics to the relevant source-code, so that users have a good introduction to the code and the barrier to contribute gets lower.

* [ ] Update source-code references (they changed since some recent big PRs)
* [ ] Compiler-checked and generated examples using mdoc (#277)
* [ ] Deploy the mdoc generated site with a good design (https://scalameta.org/mdoc/docs/docusaurus.html)

* Static Content
	* [ ] Better SVG example (Make an svg which actually shows something.)
    * [ ] custom svg tags and attributes `svgTag`, `svgAttr` (`Custom SVG attributes and tags are possible like this:`)
    * [ ] Use-Case: Absolute positioning, where parent needs to be relative

* Dynamic Content
    * [ ] Observable[Modifier], Observable[Option[Modifier]], Dynamic Attributes
    * [ ] Handler, Sink, MonixOps
    * [ ] managed, managedAction, managedElement
    * [ ] Thunk, Static
    * [ ] referential transparency
    * [ ] delayed Styles

* Emitters
    * [ ] sideEffects via foreach
    * [ ] preventDefault, stopPropagation, stopImmediatePropagation
    * [ ] debounce, async, delay, ...
    * [ ] map, withLatestFrom, useLatest, ...
    * [ ] lifecycle hooks, asHtml, asSvg (EmitterOps)

* Application Architecture Recommendations

* Gotchas
    * [ ] apply on thunks

* Advanced Stuff
    * [x] Using other streaming libraries than Monix (The example has a bug, intermediate values might get lost)
    * [ ] Streaming of lifecycle hooks
    * [ ] d3
    * [ ] fontAwesome
    * [ ] draggable
    * [ ] renderInto, renderReplace, querySelector, Element
    * [ ] Handler[Boolean], if/else
    * [ ] ifTrue[VDomModifier]
    * [ ] keys, for static input fields
    * [ ] other features from scalatags
    * [ ] Check Changelog, commits and tests for more features

**Comment by cornerman** [comment]
Need to go through this issue again to check what is done and what is still missing in the readme.

**Comment by cornerman** [comment]
> Handler[Boolean], if/else

@fdietze What is this about?

**Comment by fdietze** [comment]
> > Handler[Boolean], if/else
> 
> @fdietze What is this about?

Maybe conditionally showing something? ifTrue, ifFalse, etc?

**Comment by cornerman** [comment]
But iftrue is the next point, so it must mean something else :D

**Comment by cornerman** [comment]
I think, we have achieved this. Thank you @fdietze for the great docs we have now :)
