### ISSUE TITLE
Integrate cats

### ISSUE THREAD

**Issue by LukaJCB** [OutWatch/outwatch#28]
Currently there is no integration to cats or Scalaz, resulting in some parts of the code base not being referentially transparent. We should discuss what adopting cats means for the usability as well as other concerns like bundle size or performance.

**Comment by gaydenko** [comment]
I would vote in whole, as far as cats is widely used (scala.js supporting) library. Say, why use scala.js at all if not use cirse? :) The last want depends on cats. And so on.

**Comment by LukaJCB** [comment]
We could of course offer another module that integrates with cats and leaves the current one as is, if that turns out to be feasable. I would expect some breaking changes if we were to to adopt it in the main repo.

**Comment by gaydenko** [comment]
To my taste at early project state breaking changes are must have. I would say more: breaking changes absent is a sign of stagnation! ;)

**Comment by LukaJCB** [comment]
Another question could be if we should make `OutWatch.render` return an `IO` from the new `cats-effect` module?

**Comment by gaydenko** [comment]
@LukaJCB Do you mean a context with many mounting points and coordination of mounting/unmounting/replacing and such? If is's the case, then I can say "yes", some monadic sequencing can be valuable. 

Few yeas ago I have wrote a project (client side also, JS SPA) with rather complicated DOM parts life cycle. I was forced to write own framework (with ideas from Nicholas Zakas), and one of main point was a demand to unmount with Promise. That is the next component can be mounted after that promise is completed.

If you mean another context - can you elaborate a little, please?

(BTW, I'm not lib/typelevel man, rather app/API-user man)

**Comment by chuwy** [comment]
There's not many (none AFAIK) UI frameworks in Scala.js world that are built on top  of `cats`/`scalaz`, where developers can reuse powerful abstractions provided by FP libs to write code and inspect framework. This can be a great selling-point of Outwarch for people coming from server-side background and looking for familiar pure FP techniques in frontend - at least for me it would be a killer-feature.

**Comment by LukaJCB** [comment]
Fixed by #58
