### ISSUE TITLE
jsbin embed

### ISSUE THREAD

**Issue by ArtEze** [OutWatch/outwatch#281]
The file

http://static.jsbin.com/js/embed.js

... it has a protocol http, but should be https

https://static.jsbin.com/js/embed.js

----

Change:

This: http://outwatch.github.io/
>https://outwatch.github.io/

**Comment by cornerman** [comment]
Good point, thank you for opening an issue. I have made a PR in the website repo: https://github.com/OutWatch/outwatch.github.io/pull/13
