### ISSUE TITLE
Immediate action effects in store are applied and emitted before the action that caused them

### ISSUE THREAD

**Issue by busti** [outwatch/outwatch#289]
This issue can occur when a `Reducer` with immediate effects is used with a `Store`.  

```scala
def reducer: Reducer[Int, Int] = {
  case (5, state) => (100, Some(Observable(1, 2, 3)))
  case (action, state) => (state + action, None)
}
```
When inputting a `5` into a store with the above reducer and an initial state of 0, the expected emissions would be `0, 100, 101, 103, 106`.  
The actual emissions are `0, 1, 3, 6, 100`. (or in very very rare cases `0, 101, 103, 106, 100` depending on the scheduler used)

The first approach to solve this I have made is to move the subscription to the `effects` observable outside of the `scan` operator.  
See: https://github.com/Busti/outwatch/blob/store4/outwatch/src/main/scala/outwatch/util/Store.scala#L87-L95  

The Idea behind this change is to have the effects always use the state in store that is saved after the action that caused the emissions has been processed.  
However, the effect actions still manage to, somehow overtake the original action and emit first, causing the emissions to be `0, 101, 103, 106, 100`.  

One further thing I have looked into is to use the `flatScan` operator, but it does not really help us in this case. But it might be worth checking out its implementation.

**Comment by cornerman** [comment]
The store is now deprecated, in favor of creating the subject and pattern matching yourself. Therefore, I am going to close this one. Feel free to comment or reopen if something is missing.
