### ISSUE TITLE
Observable VDomModifier fails inspection in IntelliJ

### ISSUE THREAD

**Issue by busti** [outwatch/outwatch#291]
The following code fails to check and results in a `Type mismatch, expected: VDomModifier, actual: Observable[VDomModifier]` error in IntelliJ.

```scala
def test: Observable[VDomModifier] = ???

def view = div(test)
```  

It is just a minor inconvenience, but it might put off people new to the project.

**Comment by cornerman** [comment]
Good point. There seems to be a problem with intellij interpreting our `AsVDomModifier` and `AsValueObservable` implicits (see https://github.com/OutWatch/outwatch/blob/master/outwatch/src/main/scala/outwatch/AsVDomModifier.scala#L83). We could try reorganizing them to make intellij happy :)

**Comment by cornerman** [comment]
This fixed nowadays in intellij :)
