### ISSUE TITLE
Bump Scala version to support 2.13

### ISSUE THREAD

**Issue by busti** [OutWatch/outwatch#292]
I do not think that upgrading to ~~0.13~~ 2.13 should cause any major errors.  
I would love to make use of Scala ~~0.13~~ 2.13 collections in my app.

I will attempt to do this, this weekend (2019-03-09/P2D); I have created this issue since I do not have that much time this week.

**Comment by LukaJCB** [comment]
I assume you mean 2.13? :)

**Comment by Busti** [comment]
The changes made in #293 should technically complete this issue.  
However some dependencies of outwatch still do not compile against 2.13
Thus using outwatch with 2.13 will result in an error at the moment.

**Comment by marklister** [comment]
Commit 32564c4b97a2fdeff3a8026a607fe3406650ab1d fixes.
