### ISSUE TITLE
Exception with Observable.just in child/children

### ISSUE THREAD

**Issue by KadekM** [OutWatch/outwatch#3]
```
 div(child <-- Observable.just(div()))
```

```
"Promise already completed."

"Error↵    at $c_jl_IllegalStateException.$c_jl_Throwable.fillInStackTrace__jl_Throwable ...
```
On second patch of VDom this throws... I suppose it's because that observable has completed.

edit:

happens with deprecated `:=` as well

**Comment by LukaJCB** [comment]
Good catch! I'll have a look at it ASAP

**Comment by KadekM** [comment]
Just tried it with observable that never completes:
child <-- Observable.interval(500.millis).map(i => p(i.toString))

so I guess it's the left side?
