### ISSUE TITLE
EmitterBuilder: Adhere to Ack of Observers

### ISSUE THREAD

**Issue by cornerman** [OutWatch/outwatch#323]
As raised in #322, EmitterBuilder do not adhere to the monix protocol. We do `onNext` on an `Observer`, but ignore the returned `Future[Ack]`, which builds the backpressure protocol and tells us if we should continue or stop sending events.

Misbehaving example:
```
onClick --> new Observer[Event] { ... def onNext(e: Event) = Ack.Stop }
```

You should only get one event, because the observer returns `Ack.Stop`. But currently you actually get all events until this modifier is unmounted.

**Comment by cornerman** [comment]
I have added code to follow the backpressure protocol when sending dom-events in the EmitterBuilder, but this only solves it locally (see #347).

In general, looking at the monix documentation (https://monix.io/docs/3x/reactive/observers.html), we may never call `onNext` concurrently, which we do if we use the same `Observer` in multiple places. For example:

```scala
div(
  onClick(true) --> observer,
  onChange(false) --> observer
)
```

Each of the two emitters is fine. But in this case, both `Emitter` for click and change will send values into the same `observer`. So while the `observer` is still processing an event from a click, it might get another event from a change concurrently. As we cannot orchestrate feeding the observer over two different emitters, as those are two separate subscriptions to an observable. This cannot work, as described in the monix docs: "An observer can subscribe to at most one observable and cannot subscribe to multiple observables."

The same is true if we have an `observer` and then use this observer as well as creating a new observer with `observer.redirect` (which will subscribe to an observable). Thereby you might also end up with one observer being subscribed to two observables.

The only correct way I see right now is to require a [`BufferedSubscriber`](https://monix.io/docs/3x/reactive/observers.html#buffered-subscriber) instead of a plain [`Observer`](https://monix.io/docs/3x/reactive/observers.html#contract), because it handles concurrent access to the observer. But how do we pull this type through the API? Should a Handler be an `Observable with Observer.Sync`? Or is it now even more important to abstract over the streaming library?

**Comment by fdietze** [comment]
Is this really a problem with single-threaded javascript? Maybe `Ack` always comes back before the second emitter tries to write into the observer? Do Subjects have the same problem?

**Comment by cornerman** [comment]
I think it is a problem, because even after your `onNext` call returns, we still have a `Future[Ack]`, which you should await before sending another element to the observer.

The following is quoted from the monix docs (https://monix.io/docs/3x/reactive/observers.html):

> Feeding two elements, then stopping. This is NOT legal:
> ```scala
> // BAD SAMPLE
> observer.onNext(1)
> observer.onNext(2)
> observer.onComplete()
> ```
> The correct way of doing this:
> ```scala
> observer.onNext(1).map {
>   case Continue =>
>     // We have permission to continue
>     observer.onNext(2)
>     // No back-pressure required here
>     observer.onComplete()
>     Stop
>   case Stop =>
>     // Nothing else to do
>     Stop
> }
> ```

`

**Comment by cornerman** [comment]
Since #355, we are depending on colibri typeclasses - the problem is still there, but we accept it now.
