### ISSUE TITLE
Allow mixing of different reducer patterns

### ISSUE THREAD

**Issue by busti** [outwatch/outwatch#332]
When using a reducer with effects, for a single effect-ful action, every other action also has to return an empty observable.  
```scala
def reducer(state: M, action: A): M = action match {
  case ActionFoo => (newState, Observable.empty)
  case ActionWithEffects => (newState, Observable(ActionFoo, ActionBar)
  case ActionWithEffects => (newState, Observable.empty)
}
```  

What is your opinion on working out an alternative that makes this a little cleaner?  
There are 2 options to consider. Both involve returning a custom object, `ReductionResult` maybe? The 2 options are building it manually, or using implicits.  
So it's either:
```scala
case ActionWithEffect => ResultWithEffect(newState, Observable( /* effects */ ))
case ActionFoo => Result(newState)
```
or:
```scala
case ActionWithEffect => (newState, Observable( /* effects */ ))
case ActionFoo => newState
```

I am personally in favor of the second option, since it looks cleaner and that is the point of this suggestion.

**Comment by zakpatterson** [comment]
It seems to me the problem here is in the reducer returning a chained action. I think this is a relatively new development for this library, but I think we might want to explore going back to the `(M, A) => M` way. Or someone can clarify why reducers always create residual actions.

**Comment by Busti** [comment]
They rarely ever do, but it still is a useful feature to have.  
The thing is that I would like reducers to be able to also use `(M, A) => F[M]`, which would make things even more messy.

**Comment by zakpatterson** [comment]
That's actually an interesting point.

The motivation for the change from `(M, A) => M` to  `(M,A) => (M, Observable[A])` I think was to support async actions. Here's an example from a project I'm working on now, for just a login button. The goal is for the user to 

```scala
def reducer(state: AuthState, action: AuthAction): (AuthState, Observable[AuthAction]) = action match {
  case a: Login =>
    state.copy(authAttempt = true, error = state.error - UIError.Login) -> 
    Client
      .login(UserRequest(a.username, a.password))
      .flatMap(_ => Observable.now[AuthAction](PostLogin))
      .recoverWith{ 
         // handle login error
      }
    case PostLogin =>
      state.copy(authAttempt = true) -> Client.profile.map(UserProfile)

    case UserProfile(profile) => 
      state.copy(profile = profile.some) -> Observable.empty
```

1. User clicks button, causes `Login` action.
1. Login updates the state to show login is pending, sends ajax request to server in `Observable`, and forwards to the `PostLogin` action if login is successful
1. `PostLogin` sends another ajax request to get user's profile, forwards that to `UserProfile` action
1. `UserProfile` action updates the state with the profile returned from server, and resolves the chain with `Observable.empty`. 

If the reducer signature were changed to `(M, A) => F[M]` or `(M, A) => F[M]`, then that pending state update in 2 wouldn't happen. The state update would only happen after both ajax requests completed.

So it seems to me that the crucial part here is being able to generate intermediate states while handling asynchronous events? So maybe our reducer could be handled as `(M, A) => Observable[M]`, and our three actions above could be a single action:

```scala
  def stateReducer(state: AuthState, action: AuthAction): Observable[AuthState] = action match {
    case a: Login => 
      Observable(
        Observable.now(state.copy(authAttempt = true, error = state.error - UIError.Login)),
        (Client.login(UserRequest(a.username, a.password)) *> Observable.now(state))
          .recoverWith{
            case ClientError.Unauthorized(msg) => 
              Observable.now(state.copy(error = state.error + (UIError.Login -> msg)))
          },
        Client.profile.map(p => state.copy(profile = p.some))
      ).concat
```

So I think `(M, A) => Observable[M]` would be sufficient. What do others think?

**Comment by cornerman** [comment]
The store is now deprecated, in favor of creating the subject and pattern matching yourself. Therefore, I am going to close this one. Feel free to comment or reopen if something is missing.
