### ISSUE TITLE
@inline annotation is nothing without scala compiler enable option

### ISSUE THREAD

**Issue by zakpatterson** [OutWatch/outwatch#333]
As explained in [this lengthy post](https://www.lightbend.com/blog/scala-inliner-optimizer), `@inline` annotations only have effect if `-opt:l:inline` (1) and/or `-opt-inline-from:outwatch.*` (2) are present. 

Under the current settings, nothing is actually inlined specifically by the scala compiler. You can verify this by adding `-Yopt-log-inline :: "_" // two arguments` (3) to the list of `scalacOptions`, and then add the above suggested options, and see the new inlines. Without the 1 and or 2, there are no inlines logged. With 1 and 2, here is the output:

```
[info] Compiling 29 Scala sources to /home/projects/oss/outwatch/outwatch/target/scala-2.12/classes ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
Inline into outwatch/AsVDomModifier$ArrayModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$ArrayModifier$.asVDomModifier. Before: 9 ins, inlined: 13 ins.
Inline into outwatch/AsVDomModifier$BooleanAsVDomModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$BooleanAsVDomModifier$.asVDomModifier. Before: 9 ins, inlined: 11 ins.
Inline into outwatch/AsVDomModifier$DoubleAsVDomModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$DoubleAsVDomModifier$.asVDomModifier. Before: 9 ins, inlined: 11 ins.
Inline into outwatch/AsVDomModifier$EffectRender$.asVDomModifier: inlined outwatch/AsVDomModifier$EffectRender$.asVDomModifier. Before: 9 ins, inlined: 9 ins.
Inline into outwatch/AsVDomModifier$IntAsVDomModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$IntAsVDomModifier$.asVDomModifier. Before: 9 ins, inlined: 11 ins.
Inline into outwatch/AsVDomModifier$JsArrayModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$JsArrayModifier$.asVDomModifier. Before: 9 ins, inlined: 9 ins.
Inline into outwatch/AsVDomModifier$LongAsVDomModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$LongAsVDomModifier$.asVDomModifier. Before: 9 ins, inlined: 11 ins.
Inline into outwatch/AsVDomModifier$OptionModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$OptionModifier$.asVDomModifier. Before: 9 ins, inlined: 10 ins.
Inline into outwatch/AsVDomModifier$SeqModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$SeqModifier$.asVDomModifier. Before: 9 ins, inlined: 13 ins.
Inline into outwatch/AsVDomModifier$StringAsVDomModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$StringAsVDomModifier$.asVDomModifier. Before: 9 ins, inlined: 9 ins.
Inline into outwatch/AsVDomModifier$UndefinedModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$UndefinedModifier$.asVDomModifier. Before: 9 ins, inlined: 13 ins.
Inline into outwatch/AsVDomModifier$VDomModifierAsVDomModifier$.asVDomModifier: inlined outwatch/AsVDomModifier$VDomModifierAsVDomModifier$.asVDomModifier. Before: 9 ins, inlined: 6 ins.
Inline into outwatch/ObserverBuilder$.fromFunction: inlined outwatch/ObserverBuilder$.create. Before: 14 ins, inlined: 11 ins.
Inline into outwatch/dom/helpers/EmitterBuilder.foreach: inlined outwatch/ObserverBuilder$.fromFunction. Before: 10 ins, inlined: 32 ins.
Inline into outwatch/dom/helpers/FunctionEmitterBuilder.$anonfun$transform$1: inlined outwatch/ObserverBuilder$.fromFunction. Before: 20 ins, inlined: 32 ins.
Inline into outwatch/dom/helpers/SnabbdomOps$.subscribe$1: inlined outwatch/ObserverBuilder$.create. Before: 29 ins, inlined: 11 ins.
[info] Done compiling.
[info] Compiling 1 Scala source to /home/projects/oss/outwatch/bench/target/scala-2.12/classes ...
[info] Done compiling.
```

We could just enable this option, but the post also gives this advice: 
> Don’t enable the optimizer during development: it breaks incremental compilation, and it makes the compiler slower. Only enable it for testing, on CI, and to build releases.

We could document that our users could enable the option, including dependencies, but they're not supposed to either:
> Don’t inline from your dependencies when publishing a library, it breaks binary compatibility. Use -opt-inline-from:my.package.** to only inline from packages within your library.

So I think we have two choices:

* [ ] Remove the `@inline` annotations as they don't do anything without the compiler flag (and I think that post indicates they're of dubious value even with the setting)
* [ ] Get off of jitpack and into a typical release strategy, so that we can enable the setting in release only

**Comment by zakpatterson** [comment]
Hm it seems on further research that I'm mistaken with respect to scala,js, as it inlines in its own optimizer, but I'm still curious about the differences in log output.

**Comment by cornerman** [comment]
> Get off of jitpack and into a typical release strategy, so that we can enable the setting in release only

Good point. I think, we should use both. Jitpack for development snapshots and maven for our stable releases. @fdietze and I recently got permissions to release outwatch. And we should get back to a more regular release schedule. The overall problem is that we decided to work on version `1.0.0` way too early and are now stuck in releasing release candidates, because we are not really finished for version 1.0.0 (which would be supposed to be more stable). Either we go back to version `0.*.*` or we keep on doing release candidates. I would love to automate releasing with git-tags via travis, so we can do it easily and do it more often.

**Comment by cornerman** [comment]
> Hm it seems on further research that I'm mistaken with respect to scala,js, as it inlines in its own optimizer, but I'm still curious about the differences in log output.

Yeah, the scala-js optimizer does its own thing in regards to inlining methods and adheres to `@inline` annotations. It is really cool, and can help you build abstractions without overhead. For example with a method `@inline def map(f: Int => Unit)`, the compiler can usually inline the method and thereby avoid allocation the `f` function and just inline the code from the lambda which can be faster escpecially for tight loops.

**Comment by cornerman** [comment]
I would definitely like to keep the inlining, we can revise the methods where we do this. Furthermore, I would like investigate whether we can reduce the overhead of building the VDom with method inlining (we would need to inline definitions in `scala-dom-types` as well).

**Comment by zakpatterson** [comment]
Yep, my mistake about not understanding how the optimization works in scala.js, but I'm still confused as to why the difference in logging happens. Do you have a source about the inlining working in scalajs?

Like this project turns the option on:
https://github.com/japgolly/scalajs-react/blob/master/project/Build.scala#L45
