### ISSUE TITLE
EmptyAttributeBuilder missing?

### ISSUE THREAD

**Issue by Rockfordal** [OutWatch/outwatch#34]
I tried to implement todo list with Zurb Foundation 6
`data-close="true"` from BoolAttributeBuilder will not work

while
 -- trying to achieve:
`<button class="close-button" data-close>x</button>`
(from example http://foundation.zurb.com/building-blocks/blocks/todo-list-card.html)

**Comment by LukaJCB** [comment]
Hey, just to clarify, you tried something like `div(data.close := true)` and it didn't work, because snabbdom rendered that as `data-close="true"` instead of `data-close`? Getting that right?

**Comment by Rockfordal** [comment]
yep :)
