### ISSUE TITLE
Creating Emitters for Thirdparty Events.

### ISSUE THREAD

**Issue by pme123** [OutWatch/outwatch#36]
I was trying to add drag and drop functionality with Sortable.js ([the scala.js facade](https://github.com/Kremlianski/sortable-js-facade)).

There I like to bind the onEnd event to my redux store, something like this:
```
override val onEnd: UndefOr[js.Function1[EventS, Unit]] = (event) => {

       store <-- Observable.from(Seq(ReduxAction(event)))

}
```
This works only the first time (only after the first drop - the redux reducer is called).

Is there a correct way of emitting these actions?

**Comment by LukaJCB** [comment]
I'm not sure how Sortable.js works, but you could probably try creating an Observable with `create` and call `Observer.next` inside the function.

**Comment by pme123** [comment]
Thanks that works perfectly. Here the snippet if someone else is looking for that:
```
override val onEnd: UndefOr[js.Function1[EventS, Unit]] = (event) => {

       store <-- Observable.create(obs => obs.next(ReduxAction(event)))

}
```
