### ISSUE TITLE
Draggable does not work.

### ISSUE THREAD

**Issue by pme123** [OutWatch/outwatch#37]
Outwatch generates the draggable attribute as a boolean flag, like
```
<li draggable data-age="38">Brian Albers</li>
```
but it seems only the following is working (according to the spec there are 3 possible values "true", "false" and nothing)
```
<li draggable="true" data-age="38">Brian Albers</li>
```
I tried to add it like 
```
Attribute("draggable", "true")
```
but this creates still the boolean flag.

BTW is there a working drag'n'drop example?

**Comment by LukaJCB** [comment]
Ah this seems to be an issue with how Snabbdom deals with Boolean Attributes. I'm sure there's a way to do this in Snabbdom, but I'm not exactly sure how. Internally AFAIK Snabbdom turns Attributes with a boolean value into standalone attributes when true and removed them from the DOM node when false. I'm going to have to investigate, but it might be a bug within Snabbdom itself. We'll see :)

**Comment by LukaJCB** [comment]
Okay I think I found the culprit. It seems the Snabbdom `attrs` module cannot work with this. However the `props` module can. This is currently not really well documented in Snabbdom. What this means is that this:
```
h('div', { attrs: { draggable: "true" } })
```

results in this:

```
<div draggable></div>
```

While this:

```
h('div', { props: { draggable: "true" } })
```

results in:

```
<div draggable="true"></div>
```


So we now need to implement a way to get OutWatch to emit the latter. I'm not sure when I'll be able to start working on this, but it should be fairly easy to do :)

**Comment by pme123** [comment]
I just found: https://github.com/snabbdom/snabbdom/issues/262

That means it should be fixed. But it seems not to be released yet: https://www.npmjs.com/package/snabbdom

**Comment by cornerman** [comment]
Afaik, this is fixed and released now. As of snabbdom version `0.7.0`, boolean attributes are infered by their value type: https://github.com/snabbdom/snabbdom/releases/tag/v0.7.0. The `draggable` attribute is an `AttributeBuilder`, which sets the attribute value as string `"true"|"false"`. So, no boolean attribute magic should occur anymore. See also https://github.com/OutWatch/outwatch/pull/53.

**Comment by LukaJCB** [comment]
Awesome!
