### ISSUE TITLE
value := is not a member of outwatch.dsl.AutoStyle[String]

### ISSUE THREAD

**Issue by elyphas** [OutWatch/outwatch#403]
I have this error:
```scala
value := is not a member of outwatch.dsl.AutoStyle[String]
[error]   Expression does not convert to assignment because receiver is not assignable.
[error]                                       VDomModifier(vdomTxt, width:="300px", textAlign := "justify" ),
```
and this import:
```scala
import org.scalajs.dom.{html, _}

import outwatch.dsl._
import outwatch.helpers._
import outwatch.interpreter._
import colibri.ext.monix._
import outwatch.reactive.handlers.monix._
import outwatch.reactive.handler.{Handler => Internal}
import colibri._

//import outwatch.definitions._
import outwatch._
```
What am I doing wrong?

**Comment by cornerman** [comment]
You will need an import because styles are only working with an implicit: `import outwatch._`. It is the same as before `import outwatch.dom._`.

You do not need `outwatch.helpers._` and `outwatch.interpreter._`.

**Comment by cornerman** [comment]
But this is actually really not so nice - I will try to think of a better mechanism to not need the import.

**Comment by cornerman** [comment]
Oh, I see now that you have that import! That is confusing, we actually have tests for it - can you show me the code, because it should really work.

**Comment by elyphas** [comment]
@cornerman : here is my code:
https://gist.github.com/elyphas/462461a72ff6427fd4546da0777e9f8d

thank you the help!, :)

**Comment by elyphas** [comment]
I am going to try the other repository
//"io.github.outwatch" %%% "outwatch" % "1.0.0-RC2",
"com.github.outwatch.outwatch" %%% "outwatch" % "master-SNAPSHOT",

**Comment by elyphas** [comment]
seems I make a mistake with the repository
so far not problem.

**Comment by cornerman** [comment]
Great!
