### ISSUE TITLE
could not find implicit value for evidence parameter of type colibri.Sink[Any]

### ISSUE THREAD

**Issue by elyphas** [OutWatch/outwatch#404]
I have this error:
```scala
could not find implicit value for evidence parameter of type colibri.Sink[Any]
[error]   val onChoiceItem = Observer.combine( updateStore, cleanCatalog )
```
seems the origin is here:

```scala
  val updateStore = storeLstItems.store.contramap[(String, String)]{ case (id, desc) =>storeLstItems.UpdateIdAndDescription(id, desc) }
  val cleanCatalog = hdlCatalog.contramap[(String, String)]( _ => Seq.empty )
```
where: 
```scala
storeLstItems.store // is of type Store
//and
hdlCatalog // is of type Handler
```

**Comment by elyphas** [comment]
well seems this is the problem:
```scala
//import outwatch.reactive.handlers.monix._
import outwatch.reactive.handler._ // or outwatch.reactive.handlers.monix._
```
seems I am understanding the frp-agnostic.

**Comment by elyphas** [comment]
I am getting other errors:
```scala
value distinctUntilChanged is not a member of colibri.Observable[String]
[error]       e.debounce(800 milliseconds).distinctUntilChanged
```
```scala
 value mapSubject is not a member of outwatch.reactive.handler.Handler[Int]
[error]           cmpInput("Ejercicio", hdlEjercicio.mapSubject[String](_.toInt){ f: Int => if (f <= 0) "" else f.toString},
```
I need to use monix without colibri, am I right?

**Comment by elyphas** [comment]
then I need to change all 
```scala
Observer.create[ // from colibri
//with
new Observer // from monix.
```
to fix it, am I right?

**Comment by elyphas** [comment]
Then this arise another question:
How can I combine observer monix?
I use to do this:
```scala
  val updateStore = storeLstItems.store.contramap[(String, String)]{ case (id, desc) => storeLstItems.UpdateIdAndDescription(id, desc) }
  val cleanCatalog = hdlCatalog.contramap[(String, String)]( _ => Seq.empty )

  val onChoiceItem = Observer.combine(updateStore, cleanCatalog)
```

**Comment by elyphas** [comment]
well at this moment I going to try:

```scala
class GridCatalogs {
  def render ( values: Map[String, String], pos: (Int, Int), onClickItem: List[Observer[(String, String)]])
}

grid.render(items, pos,  List(observerIdAndDesc, cleanCatalog) )
onClickItem.map( obs => onClick.use( ( k, v ) ) --> obs)
```
altough I can't see if is working fine until my app its compiled because it have some errors. :)

**Comment by cornerman** [comment]
>  How can I combine observer monix?

You can lift a monix observer to a colibri observer, like this: `Observer.lift(monixObserver)`. Or you can combine different kinds of observers with: `Observer.combineVaried(monixObserver, colibriObserver)`.

**Comment by cornerman** [comment]
> I need to use monix without colibri, am I right?

Not necessarily, `mapSubject` is indeed not there, but you can do `transformSubject` like `transformSubject(_.contramap(f))(_.map(g))`.

**Comment by elyphas** [comment]
ah thank you

**Comment by cornerman** [comment]
Does that fix your problem? :)

**Comment by elyphas** [comment]
still don't know, I have another problems.
and at this moment those errors doesn't appears.
and Because I changed to `new Observer`

**Comment by elyphas** [comment]
I have this problem:
[https://github.com/OutWatch/outwatch/issues/405](url)

**Comment by elyphas** [comment]
[405](https://github.com/OutWatch/outwatch/issues/405)

**Comment by elyphas** [comment]
solved
@cornerman ; thank you
