### ISSUE TITLE
Document lifecycle management

### ISSUE THREAD

**Issue by mvh77** [OutWatch/outwatch#43]
Hi!

I saw your presentation from Curry On, nice work! I read through the docs this week-end and I'd like to see something about how life cycle management is handled. I've previously used udash, Scala.rx and even had a peek at Binding.Scala. Scala.rx has the concept of [context](https://github.com/lihaoyi/scala.rx#ownership-context) to prevent leaks whereas Binding [does some other magic](https://github.com/ThoughtWorksInc/Binding.scala#lifecycle-management-for-data-binding-expressions). How's this done in outwatch?

**Comment by fdietze** [comment]
Does Monix implement such a concept?

**Comment by cornerman** [comment]
Fixed in #355
