### ISSUE TITLE
Testing UIs with Outwatch

### ISSUE THREAD

**Issue by elsehow** [OutWatch/outwatch#44]
Hi all!

Outwatch looks fantastic, I can't wait to try it out.

I was wondering what the standard practices are around testing for Outwatch. Since Outwatch is really quite functional, it seems like I should be able to test it without having to worry about stateful stuff like the DOM. So, can I test my Outwatch UIs in some virtualized DOM environment, without having to muck around with ScalaJS/jquery stuff?

**Comment by LukaJCB** [comment]
You can check out the tests in this repo, they should help you get going :) https://github.com/OutWatch/outwatch/blob/master/src/test/scala/outwatch/ScenarioTestSpec.scala

**Comment by elsehow** [comment]
Thank you!
