### ISSUE TITLE
Add append and prepend methods to Modifier

### ISSUE THREAD

**Issue by cornerman** [outwatch/outwatch#443]
Like we have on VNode. Though probably not adding the `apply` alias for append on modifiers.

Question: Would that confuse users? Because append and prepend on VNode puts the new modifier into the VNode, though for Modifiers, it would just append/prepend to the modifiers.

**Comment by fdietze** [comment]
We could also make VDomModifier an immutable Seq that integrates with Scala collections to get certain collection operations, including append and prepend for free.

**Comment by fdietze** [comment]
Or make VDomModifier an alias for Seq[VDomModifier]

**Comment by cornerman** [comment]
You can already just work with `Seq[Modifier]` - which is as you said probably the nicest way to interact with.
A type alias would not really work afaik, because then eveything must be wrapped in a Seq, which would cost allocation.

**Comment by busti** [comment]
I remember having to use the `Monoid` instance of `Modifier` before to do this, so this would definitely come in handy.  
Would this change still require the methods to be on `VNode` aswell? I do not think it would be that confusing if the methods just moved somewhere else.

**Comment by cornerman** [comment]
@busti We have them on `VNode` as well to narrow down the type of `append` and `prepend` to be `VNode` and not just `Modifier`. We do this, because some parts of our API like `OutWatch.render` or `thunk` need a `VNode` and cannot just work with `Modifier`. Also, the `apply` method would only be defined on `VNode` though it is just an alias for `append` (maybe should also be defined on Modifier?).

**Comment by busti** [comment]
I was originally going to say
> Having it on `Modifier` would make for some awkward syntax imo, i.e. `val modifier = (className := "foo")(id := "bar")`

But I actually do not think it is that bad.  

Regarding the type narrowing, that would basically just make them overridden methods, which is still transparent.
