### ISSUE TITLE
Need to be able to sink to DOM Object properties, not only attributes

### ISSUE THREAD

**Issue by pfn** [OutWatch/outwatch#45]
Properties and attributes of elements can go out of sync.

```scala
  val checkToggler: Observable[Boolean] = ???
  val checkToggled: Sink[Boolean] = ???
  input(tpe := "checkbox", checked <-- checkToggler, inputChecked --> checkToggled)
```

repro:

1. click on the checkbox
1. send a message to checkToggler
1. observe `checked` dis/appearing on the DOM attribute when checkToggler is sent
1. observe the value of the `checked` property on the input

`inputChecked` emits events using the value of the `checked` property on the element; manual user toggling only modifies the element property as well.

plain fiddle reproduction http://jsfiddle.net/mxzL2/9/

**Comment by LukaJCB** [comment]
Fixed by 55687e9204f708ab7b1525d002143950ed0b826e :)
