### ISSUE TITLE
Style guide/rules

### ISSUE THREAD

**Issue by cornerman** [outwatch/outwatch#452]
~~We have a scalastyle config and reference it in `Contributing.md`, but do not actually use it.~~ We should/could actually use a formatter. Or we decide to not use a formatter and remove it from the contributing guide.

**Comment by busti** [comment]
Maybe we should consider switching to scalafmt first. 
Scalastyle is pretty much abandonware and scalafmt is quite powerful, although it lacks documentation.  
That being said, I like scalastyle. I have always found it easier to make it do what I want, but there have been some improvements to scalafmt recently that fixed that. 
Also the language aware features of scalafmt are really nice.  

Thoughts?

**Comment by fdietze** [comment]
Scalafmt sounds good, let's add it after merging #441
