### ISSUE TITLE
Move managed functions into Modifier companion

### ISSUE THREAD

**Issue by cornerman** [outwatch/outwatch#454]
Currently we have helpers like `managed`, `managedFunction`, `managedElement` as part of the DSL, but I think, they would be more accessible and explorable if they were part of the `Modifier` companion. So use them via `Modifier.managed*`. You get better autocompletion with it and everything is one place.

What do you think?

**Comment by fdietze** [comment]
I like it. It means less pollution of the namespace and completion is a good argument!

**Comment by cornerman** [comment]
Fixed in #593
