### ISSUE TITLE
Managing external elements

### ISSUE THREAD

**Issue by s5bug** [OutWatch/outwatch#478]
Trying to use a `math-field` from MathLive. The ways you're normally supposed to use it:
1. Have a `<math-field>` baked into the HTML, which will be scanned for on a page load event.
2. Create a `new MathfieldElement()`.

The `<math-field>` won't work as I'm creating elements at runtime, and the `new MathfieldElement()` mostly works with `VNodeProxyNode` but has a few shortcomings. Once the element is mounted, I need to set its `value` to a math expression. This requires getting the element at runtime, which cannot be done with `VNodeProxyNode`.

**Comment by fdietze** [comment]
Sorry, for this late answer. You can access the raw dom node like this:

```scala
div(
      managedElement.asHtml { elem =>
        // do something with the html element

        Cancelable { () =>
           // clean up
        }
      }
)
```

**Comment by s5bug** [comment]
This didn't work for me for setting initial properties. Eventually I was able to use
```scala
    val expressionBox = new mathlive.MathfieldElement()
    val expressionBoxVNodeProxy = snabbdom.tovnode(expressionBox.asInstanceOf[dom.Element])
    val expressionBoxVNode = VDomModifier(VNodeProxyNode(expressionBoxVNodeProxy), onDomMount.foreach { elem =>
      val input = elem.getElementsByTagName("math-field")(0).asInstanceOf[mathlive.MathfieldElement]
      input.id_=(expressionBoxId)
      input.value_=("f(z) = z^2")
    })

    val container = div(inputCanvas, outputCanvas, expressionBoxVNode, idAttr := "app")

    val render = OutWatch.renderReplace[F]("#app", container)
```
which seems to work just fine.
