### ISSUE TITLE
Drop the optional attr builder methods in favor of overloading

### ISSUE THREAD

**Issue by busti** [outwatch/outwatch#526]
Constructing an attr from an `Option[_]` or an `Observable[Option[_]]` currently requires users to use the `:=?` and `<--?` methods.  
Several people I have spoken to are weirded out by this quirk specifically.  

Why do we have them anyways? Why not just have `:=` and `<--`
Couldn't we just merge the two names into 2 different definitions of the same name?

**Comment by fdietze** [comment]
I agree. I even think we should only have `:=`, which accepts everything you mentioned.

**Comment by busti** [comment]
I like `<--` as an analogous to `-->` in `EmitterBuilder`.  
I feel like it signals the intent of a changing value better, but then again most people will probably just `map` over a state observable.

**Comment by fdietze** [comment]
We already dropped the syntax for streaming children of a vnode, because we decided that Observables can just be used like VDomModifiers. Doing the same for attributes would be more consistent in my opinion and it's less syntax in general.

Afaik, the laminar syntax was inspired by outwatch :)

**Comment by busti** [comment]
Yeah, let's drop it.  
I cannot really imagine any real use-case for `<--` anyways, that wouldn't be better served by `.map`

**Comment by cornerman** [comment]
I have removed the optional builder methods with `?`, but kept the distinct between `:=` and `<--` for now - i could not really get it to work properly with overloading. We can open another issue for that
