### ISSUE TITLE
bug in `debounceMillis`

### ISSUE THREAD

**Issue by FloWi** [outwatch/outwatch#538]
It seems like the last event gets lost while debouncing.

Screenshot taken from the example (here)[https://outwatch.github.io/docs/readme.html#example-input-field]
![image](https://user-images.githubusercontent.com/39078/139843742-b5d776d3-f695-4461-9207-8a56224973e8.png)

**Comment by FloWi** [comment]
Maybe Foobar is having a bad day at work... ;-)

**Comment by cornerman** [comment]
Thank you! The example was not doing what was expected. I have fixed the documentation now.
