### ISSUE TITLE
Doc suggestion: Word-based diffs

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#54]
Having a diff to highlight the code changes is great. One could go even further and use a word-based diff instead of a line-based diff. This would remove a lot of visual clutter.

Git can do this: https://git-scm.com/docs/git-diff#git-diff---word-diffltmodegt
As a word-regex I suggest: `[A-Z][a-z]*|[a-z]+|[^[:space:]]` which can even seaparate Words written in CamelCase.

**Comment by fdietze** [comment]
A library like https://github.com/kpdecker/jsdiff could help.
One could even preserve syntax highlighting by marking the added/removed parts with colored borders.

**Comment by cornerman** [comment]
Is this relevant still?

**Comment by fdietze** [comment]
I don't think so. The tutorial is outdated.
