### ISSUE TITLE
Show and print errors of `Observables` / `IO` by default

### ISSUE THREAD

**Issue by fdietze** [outwatch/outwatch#544]
I had many cases now, where an error was thrown in an `IO` or `Observable`, but I didn't notice, because then the rendered element was just not shown.

I think unhandled errors should be displayed by default, because silent fails are difficult to debug.

**Comment by cornerman** [comment]
Very good issue. Wanted to create one too. Because somehow our printing of errors is broken.

Do you think, rendering an error element is even better?

**Comment by fdietze** [comment]
I think we should do both (rendering and printing to console) to make unhandled errors as visible as possible.

**Comment by cornerman** [comment]
Yeah, we could even make the error-element configurable, and then you can also set it to `VModifier.empty` - if you do not want it.

**Comment by fdietze** [comment]
I think people should just handle the errors if they don't want to see them. `IO` and `Observable` provide many handy tools for that.

**Comment by cornerman** [comment]
True.
