### ISSUE TITLE
This looks a LOT like Cycle.js

### ISSUE THREAD

**Issue by Frikki** [OutWatch/outwatch#6]
Even the docs.

**Comment by Frikki** [comment]
But it’s cool!!! :heart:

**Comment by LukaJCB** [comment]
Thank you! Andre Staltz and the Cycle.js community have been a huge influence on the work put into OutWatch. RxJS, Cycle.js and Elm really introduced me to the concept of using streams to write declarative UIs. Naturally I wanted something similar for Scala and so started work on a concept of something like a framework based on Rx. And OutWatch is the result of that. 

There are quite a few significant differences between Cycle and OutWatch even apart from the language, opting for different tradeoffs on some issues. 

I love Cycle.js and Rx or any stream library and I love working with these technologies so the more pop up in the future, the happier I am. :)
