### ISSUE TITLE
support apply, prepend, append on F[VNode]

### ISSUE THREAD

**Issue by fdietze** [outwatch/outwatch#623]
I'd like to be able to write this:

```scala
val x:Observable[VNode] = Observable(div("hello"))
x.append(marginLeft := "50px")
```

**Comment by cornerman** [comment]
We can do that and add it to every `F[VNode]`, where `F` is `Functor`. I would then add this to an import like `outwatch.implicits._`.

**Comment by fdietze** [comment]
Yes, that sounds like a good solution! Will it also work for `F[F[VNode]]` or `F[F2[VNode]]`?

**Comment by cornerman** [comment]
Yes, you can do that now with `import outwatch.implicits._`. It works for `F[VNode]` and `F[G[VNode]]`, where `F` and `G` are a `Functor`.

**Comment by cornerman** [comment]
Turns out, I will have to revert this. It works in scala 3, but not in scala 2.13. That is because we still have this implicit conversion to `VModifier`, which somehow gets prioritized over the newly introduced implicits. This can only be done when fixing this: #354
