### ISSUE TITLE
cls.toggle is not very nice to use.

### ISSUE THREAD

**Issue by busti** [outwatch/outwatch#641]
I feel like `cls.toggle` is in stark contrast to other class definitions in outwatch.  
Take a look at the following code:  
```scala
val disabled: Rx[Boolean] = ???

button(
  cls := "btn",
  cls.toggle("disabled") <-- disabled
)
```

It feels like this should be the other way round. `cls.toggle(disabled) := "disabled"`.

**Comment by cornerman** [comment]
Do you have a good idea for another name or should we just repurpose the method?

**Comment by busti** [comment]
I am not sure if and how we could handle it cleanly.  
We could just inverse the relation, but since we have both `<--` and  `:=` that isn't very nice.  
Maybe we should really get rid of `<--` first.

But constructs like `cls.toggle(someRx) := someRxOfString` can still exist which is kinda ugly.

**Comment by fdietze** [comment]
Agreed to get rid of `<--`.

Another syntax could be:
```
(cls := "disabled").toggle(someBoolRx)
```

**Comment by cornerman** [comment]
I do not feel that strongly about `<--` and until now we did not manage to write proper overloads for the `:=` function - so I would put this on hold for now.

We could use the same construct as with VModifier.ifTrue(...)(...). Thereby, we can make the second parameter list call-by-name and thereby lazy. This is useful if we are toggeling bigger VModifiers - that you do not want to construct when you do not render them.

**Comment by busti** [comment]
I think we should make an effort to keep this feature concise. It is mostly a convenience feature anyways and should flow nicely with other class declarations.  
If it weren't present at all one could also do the following:  
```scala
div(
  someObservableBool.map(b => Option.when(!b)(cls := "disabled"))
)
```

**Comment by cornerman** [comment]
On that note. We should align with the std library (Option here) and rename VModifier.ifTrue to when and ifNot to whenNot.

**Comment by cornerman** [comment]
Good point about concise. How about we keep it similar and even name it when. Toggle is a bit ambiguous anyhow.
 
 div(
  cls.when(Boolean or Observable[Boolean]) := "disabled"
)

**Comment by cornerman** [comment]
An alternative could be to add operators to colibri for observables. Something like this:

```
div(
  // could also be named ifElse/ifElseEmpty
  boolObservable.whenOr(cls :=  "disabled", VModifier.empty)
  // or even for monoid
  boolObservable.whenOrEmpty(cls := "disabled")
)
```

**Comment by cornerman** [comment]
The `toggle` method is now deprecated without replacement :)

Please reopen if you think, we still need something else than `asIf`.
