### ISSUE TITLE
Rename EmitterBuilder.mapResult -> mapModifier ?

### ISSUE THREAD

**Issue by fdietze** [outwatch/outwatch#646]
https://github.com/outwatch/outwatch/blob/06c4cca2af43313a7062fbeb149ac2bf22e90b5e/outwatch/src/main/scala/outwatch/EmitterBuilder.scala#L243

**Comment by cornerman** [comment]
In understand it, but currently an emitterbuilder could also return a VNode or something totally different. `mapModifier` would not capture that. Is there a better name that leaves that open?

**Comment by cornerman** [comment]
Everything, that can own a subscription :)

**Comment by fdietze** [comment]
Sounds a bit too generic to me. Is there a good use-case?

**Comment by cornerman** [comment]
One example, the typeclass allows us to return any `Functor`, like an `Option`, a `List` or `IO` of a Modifier as a result. Furthermore, you could also return something totally different like an `Observable[Something]`, because they can also own a subscription. I had a use-case once - though not very common.

**Comment by cornerman** [comment]
I guess, it is debatable whether we need to support that - but I did not see a reason why not. We anyhow need to keep it generic to have a distinction between `VNode` and `VModifier`.

**Comment by cornerman** [comment]
Do we have a better name than `mapResult` that stays generic?

**Comment by fdietze** [comment]
`mapContainer`, `mapOwner`, something like that? `Result` is misleading imho.

**Comment by cornerman** [comment]
Will close this for now. If we end up rewriting EmitterBuilder one day, we can maybe do something else.
