### ISSUE TITLE
Occasional weirdness in DOM updates

### ISSUE THREAD

**Issue by KadekM** [OutWatch/outwatch#7]
To reproduce:

https://github.com/KadekM/outwatch-playground/blob/master/src/main/scala/Outwatchplayground.scala

It seems to reuse the same observable (not attach new one), which seems to cause mentioned problems...

**Comment by raquo** [comment]
I've just started wrapping my head around Outwatch's internals, but I think a possible reason for this is that Outwatch creates the subscription in snabbdom's `insert` hook, which fires only when a new DOM element is created (not when a new _VNode_ is created). So if snabbdom chooses to reuse the same DOM node, which is probably the case here, the insert hook will not fire. Same for destroy hook. And as you said, we're left with the old subscription.

**Comment by pme123** [comment]
I have the same or similar problem:
`children <-- Observable.from(Future(uiEntity.parameterEdit()))`
uiEntity.parameterEdit() creates a Seq of VNodes. The uiEntity changes, but in the UI the parent element shows still the first VNodes, that were shown the first time (when loading).
Btw: this is the only way I saw to add a Seq of VNodes. Why is something like
`children := uiEntity.parameterEdit()` not possible?

**Comment by LukaJCB** [comment]
Hey @pme123, yes, that is indeed confusing. However it is possible. Instead of doing `children := ...` you can expand a `Seq` into varargs by annotating them with `: _*`. So something like `div(uiEntity.parameterEdit(): _*)`

**Comment by pme123** [comment]
thanx, that was exactly what I was looking for. (BTW: great project!)
