### ISSUE TITLE
Provide streams to interact with current URL

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#72]
To help constructing routers, provide streams to read from and write to the URL of the browser. Analogous to LocalStorage.

**Comment by fdietze** [comment]
This could be inspired by parts of: https://github.com/mariusmuja/outwatch-extras

**Comment by cornerman** [comment]
There is [outwatch-router](https://github.com/clovellytech/outwatch-router), now. So I think, this is nicely handled inside a third-party library.
