### ISSUE TITLE
Move snabbdom facade to separate project

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#73]
This in combination with scala-dom-types would make the codebase of outwach much simpler.

**Comment by cornerman** [comment]
Files in the `snabbdom` package should not depend on outwatch. Eventually, this would make it possible to move snabbdom to a different repo.

Currently, it depends on `outwatch.dom` in these places:
- https://github.com/OutWatch/outwatch/blob/master/src/main/scala/snabbdom/h.scala#L115
- https://github.com/OutWatch/outwatch/blob/master/src/main/scala/snabbdom/VDomProxy.scala

**Comment by cornerman** [comment]
As is, we use a fork of snabbdom and additionally made some amendments to the facade. Therefore, this does not really apply anymore.

**Comment by fdietze** [comment]
It could still make sense to have the facade in a separate sbt sub-project.

**Comment by cornerman** [comment]
Sure, we can do that :)
