### ISSUE TITLE
Provide compatibility import for using outwatch without IO

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#75]
Something like:

```scala
import outwatch.domUnsafe
```

**Comment by mariusmuja** [comment]
I'm not sure if this is a good idea. Having two ways of using outwatch would just increase the confusion and complicate code reuse. 

I think that keeping VDom building with the referential transparent API very close to the way it's done with the non-referential transparent API, migration should be easy enough, in most cases it's just replacing:
```scala
val handler = createHandler[T]()
...
```
with 
```scala
createHandler[T]().flatMap { handler =>
..
}
```

**Comment by fdietze** [comment]
Right now I'm migrating a large codebase from scalatags to outwatch. Introducing Outwatch and IO at the same time made it too complicated. So I ended up running all IOs manually, to introduce the IO concept later. A simple import would have helped in this case. Sometimes `sink <-- observable` does compile but is not executed because of this.

Any Ideas?

**Comment by mariusmuja** [comment]
Maybe something like [Monadless](http://monadless.io/) could help in such cases?

**Comment by fdietze** [comment]
The Syntax-Sugar of Monadless looks great, but you still have to connect IO-Code with side-effecting code. We tried first, but that was not trivial at all, so we decided against it.

**Comment by cornerman** [comment]
I think, the latest refactoring leads to a less intrusive interface, where there are only effect types used when really necessary. You can opt out of Handler being IO by using `Handler.unsafe` or just creating your own Subjects via the monix API. Therefore, this is not needed anymore.
