### ISSUE TITLE
Wrap Sink.create in IO!

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#81]
I noticed that Sink.create() does not return an IO. Is this on purpose?

**Comment by cornerman** [comment]
Furthemore, we need cleanup up some remainings of the IO port. There are still [some `unsafeRunSync()` left in the code](https://github.com/OutWatch/outwatch/search?utf8=%E2%9C%93&q=unsafeRunSync+path%3Asrc%2Fmain%2Fscala&type=).

**Comment by cornerman** [comment]
What about this?

**Comment by cornerman** [comment]
@LukaJCB @mariusmuja can one of you enlighten us? :)

**Comment by LukaJCB** [comment]
Yeah it should probably be in IO :)
