### ISSUE TITLE
Provide observers for global eventhandlers

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#89]
Instead of using global event handlers with callbacks, provide lazily created Observers for the Events.
Proposal:

```scala
lazy val documentOnLoad = {
  Observable.create[Event] { observer =>
    document.onload = observer.next
  }
}
```

**Comment by cornerman** [comment]
This should be possible with `scala-dom-types, as there we already have all window events there: https://github.com/raquo/scala-dom-types/blob/master/shared/src/main/scala/com/raquo/domtypes/generic/defs/eventProps/WindowEventProps.scala. We just need to construct them as proposed or pass them as eventemitters to snabbdom.

**Comment by fdietze** [comment]
RxJS has something similar: https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/modules/main-events/readme.md

**Comment by cornerman** [comment]
With the next version of domtypes, we will be able to do this. We could expose DocumentEvents.{onLoad, onInput, ...} and WindowEvents.{onStorage, onHashChange, ..., onLoad, onInput, ...}. These can be build like the example above. For the elements, we can have the event properties in the `dom` package. So you can still do `div(onLoad -->, onInput --> ...)` for building snabbdom nodes.
