### ISSUE TITLE
Observable Diamond data flow

### ISSUE THREAD

**Issue by fdietze** [outwatch/outwatch#92]
I want to model this dataflow without *frp glitches* or too many updates:
```
c --> b --> d
      ^     ^
     /     /
    a------
```

scala.rx handles this well:

```scala
@ import $ivy.`com.lihaoyi::scalarx:0.3.2`, rx._
@ val (a,c) = (Var(0), Var(0))
     val b = Rx{ (a(), c()) }
     val d = Rx{ (a(), b()) }
     d.foreach(println) 
(0,(0,0))

@ a() = 1 
(1,(1,0))

@ c() = 5 
(1,(1,5))
```

But I have trouble modeling this with rxjs. Any ideas?

**Comment by LukaJCB** [comment]
So the issue is, that:
```
>var a = new Rx.BehaviorSubject(0)
undefined
>var c = new Rx.BehaviorSubject(0)
undefined
>var b = a.combineLatest(c)
undefined
>var d = a.combineLatest(b)
undefined
>d.subscribe(n => console.log(n))
[0, [0, 0]]
>a.next(1)
[1, [0, 0]]
[1, [1, 0]]
undefined
>c.next(5)
[1, [1, 5]]
undefined
```

`d` is triggered twice here?

**Comment by fdietze** [comment]
Exactly. d is triggered twice and the intermediate triggers represent
inconsistent data.

On 14 Nov 2017 17:35, "LukaJCB" <notifications@github.com> wrote:

So the issue is, that:

>var a = new Rx.BehaviorSubject(0)
undefined
>var c = new Rx.BehaviorSubject(0)
undefined
>var b = a.combineLatest(c)
undefined
>var d = a.combineLatest(b)
undefined
>d.subscribe(n => console.log(n))
[0, [0, 0]]
>a.next(1)
[1, [0, 0]]
[1, [1, 0]]
undefined
>c.next(5)
[1, [1, 5]]
undefined

d is triggered twice here?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OutWatch/outwatch/issues/92#issuecomment-344317017>,
or mute
the thread

**Comment by fdietze** [comment]
Closing this, since this is not how Observables are designed. To model these dataflows, use Scala.rx or Airstream (not supported by outwatch yet)
